<?xml version="1.0"?>
<!DOCTYPE kitabxana [
  <!ELEMENT kitabxana (kitab+)>
  <!ELEMENT kitab (ad, muellif, il)>
  <!ELEMENT ad (#PCDATA)>
  <!ELEMENT muellif (#PCDATA)>
  <!ELEMENT il (#PCDATA)>
]>
<kitabxana>
  <kitab>
    <ad>Harry Potter</ad>
    <muellif>J.K. Rowling</muellif>
    <il>1997</il>
  </kitab>
</kitabxana>
